### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by hotnuts21** [OverByThere/rnlipager#1]
Can I ask, are you scraping the desktop page for the data or are you getting it direct from the RNLIs desktop page feed?

thanks
Paul

**Comment by OverByThere** [comment]
Hey @hotnuts21 (same as [sankesolutions](https://twitter.com/sankesolutions)?), I'm scraping the data direct from the RNLI services system, which runs on the [Latest Launches](http://rnli.org/latestlaunches/Pages/latestlaunches.aspx) page:
![RNLI Launches network](http://i.imgur.com/NqgRniP.png)

Hope this helps, if you need anything else please do let me know.

Dan

**Comment by hotnuts21** [comment]
Yep same as Sankesolutions how did you make that connection :-0

Ahh been looking for that URL ;-)  Many thanks for the heads up!

**Comment by OverByThere** [comment]
No problem! Feel free to raise any further issues if you have any questions :)
